name: 自动部署

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: SSH 登录服务器并更新代码
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: 120.48.9.224
          username: root
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            cd ~/tts_app
            git pull
            systemctl restart tts_app
